services:
    api: &api
        image: caju-beneficios-api:latest
        container_name: api
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            DATABASE_HOST: mongodb://mongodb
        depends_on:
            - mongodb
        ports:
            - ${APP_HOST_PORT:-8000}:${APP_HOST_PORT:-8000}

    prometheus:
        image: prom/prometheus:v2.52.0
        container_name: prometheus
        volumes:
            - ./.monitoring/prometheus/:/etc/prometheus/
        depends_on:
            - api
        ports:
            - 3000:9090

    grafana:
        image: grafana/grafana:11.0.0
        container_name: grafana
        environment:
            GF_AUTH_ANONYMOUS_ENABLED: 1
            GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
        volumes:
            - ./.monitoring/grafana/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
            - ./.monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
        depends_on:
            - prometheus
        ports:
            - 3001:3000

    mongodb:
        image: mongo:8.0.1
        container_name: mongodb
        command: mongod --replSet rs0
        environment:
            MONGO_INITDB_DATABASE: caju_beneficios_api
        volumes:
            - mongodb:/data/db
            - mongodb:/data/configdb
        ports:
            - 27017:27017

    mongodb-init:
        image: mongo:8.0.1
        container_name: mongodb-init
        command: >
            mongosh --host mongodb:27017 --eval 
            '
            rs.initiate(
                {
                _id : "rs0", members: [
                    { _id : 0, host : "mongodb:27017" }
                ]
                }
            )
            '
        depends_on:
            - mongodb

    runner:
        <<: *api
        command: /bin/ash

volumes:
    mongodb:
