groups:
  - name: CajuBeneficiosApi Alerts
    rules:
      - alert: ApiHealth
        expr: up{job="CajuBeneficiosApi"} < 1
        for: 5s
        labels:
            severity: critical
        annotations:
            summary: Api HealthCheck
