kind: Secret
apiVersion: v1
metadata:
    name: caju-beneficios-api-secrets
    namespace: production-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:gXcToxs=,iv:YBqU+mS/08tMHMU7D4ZOILdY/qjD7EHfgCgiOvfMZmE=,tag:KZ0bN/qvogkdLXedHv6RaQ==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:RYBa0qymLXvgMQ==,iv:YMGJtOVeb5Ng+L1PKtJ0whJVuxCOxh9FVlfmN0lwCg4=,tag:uGpVKiWwLxCJGiXU9ZpLJA==,type:str]
    APP_HOST: ENC[AES256_GCM,data:usaqSHYt4Q==,iv:xws12xir38vF2Mdx3PlWLHN557H+XHVIHdxczEwkWoM=,tag:mkEcIFTZIzydMCZxlt9Peg==,type:str]
    APP_HOST_PORT: ENC[AES256_GCM,data:sXnzbw==,iv:o6bWXRXENyV62lr9ve64hzqew5Ilc+Ayhs6J4tFYQa8=,tag:bNgXB1Bs+0AuLGrQ1+O08g==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:mHRyOgU=,iv:bQEy7XpkXl4fooL9k8kRet41qguwwLa69kAlYWpF9TY=,tag:vMaSRG5eRZOFNIjzayoz+Q==,type:int]
    DATABASE_HOST: ENC[AES256_GCM,data:FyCyhr8UOlg8TNWrprzW1fo=,iv:YtzZDU3WTu3zywfiMpSLQPxetbKuNniNjr8v6/rInKo=,tag:1BmrcQOEvSGTmOy6kG5iIQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:wZp2J8hodulwe6AOGJYcUKK58A==,iv:/KLvEW5wzmiVDEvNVqHtR2YNxlkuP7fAqz1xCMPJa/c=,tag:HEdMWsL4FxFQ8m88muQZsg==,type:str]
    DATABASE_PARAMETERS: ENC[AES256_GCM,data:rgn0JeWWl5wwOLkpqkzQYmnpMpiAzqxzmme+G7iOlTk/NfeJcmV/ALaBDtq8dhSr+bDA8MtzzN9oueckPNV0ONTIzur+xqWxsPerT+ydHtDTyCPcia/kmVtdPd9CI0eITDhmrb5lwVz8YoSTxaclIUWo7XOIIhxc4qLW8kNAHMO6NEc4OTXhPhLk2fZA8DQxCWYHdCIWAWo=,iv:w+VC18joPl0sKijTD0xhYt2FMWgG0rr0qaVVO0cIo0U=,tag:wW1xYhGfb1dL9baf21GTng==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:RoGUjjAUNeIDZ7X/x277XN2CqdLgDR3XOMGaqDJQ7ZcXg3yv,iv:jqzVN5rTrB8zCYrlrSS9HtslrPIPHBr4tmJGnV7/yV4=,tag:qeFv3BJlrhXLoqJxjjdJ1g==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:zI7tu3E=,iv:8GwVWQlcvZNGaHQONH01zXGJiIHGmJFRMyeh+WD3avw=,tag:JoTy14GjF47scZu9IR+m8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTGpTQzlBQzhsZlhwYzRO
            QlJ1dXY3U09vMG84ODZaeUx3VGF6UmRUdTNNClA1Z1VNNXZYcXhiVi85UEV5eW83
            OG0zZ25wKy9OVlVJOTl3S0hUc0hnalUKLS0tIGphQ3VnNE5xbGlXSGJBQndzeWpz
            YzF0MlpqVCtraU5vaDJuU3N0aHlSdmcKRBF94nFE0vcC1QzxUfebeOYqpQzEGM0k
            6sEuqgWDUgN/XRz0h2aOr/MI+sm6SZ3IRfOd3kpdMyUzB4+TpNmcDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T14:52:53Z"
    mac: ENC[AES256_GCM,data:ela69p5cPBxQ09MD+T8P0yxYxjgoZgQlZpgrFmnXqEndasEKpyp+Y/urY9gLiM8fKH3O2KV74T41rYxtXgsiRvNaTYO/d82N0xgCFjOzgtmpG3mvXYQJ0H4DPUUIGUoyMLP0mTDTkL43sBy3ZXpZv+FCFsuUoQfCiAl85eN8tg0=,iv:MjeJinenu+qnjpYm/Hfgvao58Goq3ujsMV9eD1kogFY=,tag:Cuf8gNZWS6zlgPKg16ucdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
