kind: Secret
apiVersion: v1
metadata:
    name: caju-beneficios-api-secrets
    namespace: staging-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:D84pAw==,iv:HvV2MWyuh3DJVz9MAM27EpbFDG22vUT+YsrbA+1kLM8=,tag:rrGN8/RSV0dPy6il4jWr/g==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:lQCq16t0Hw==,iv:9SNTG6ORwk/tCgPV+Zxjy4HgL20JtxGMtoATvI/dyXc=,tag:ODI9g+rm0+6fUmTrUUMKjg==,type:str]
    APP_HOST: ENC[AES256_GCM,data:Uayvmm7UnA==,iv:4aP8c9VQF8LTEdKmq6HydTABH5o3Bu0v511Mw0qgTg4=,tag:DGFCPXKdDYL8G/lSMN54sQ==,type:str]
    APP_HOST_PORT: ENC[AES256_GCM,data:z6bu0Q==,iv:g3FzNUKqKqLB6YCm+0LvGlpJ2UnWRiFS9YNoLV26K5U=,tag:rmwLJN7HRJf7iDVUR6LI7A==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:QiKaaOg=,iv:iWpzZsNLI/CrOvDqdQZPI/ioqdDzTD3XJo0RYumaQWo=,tag:fRMpBO2IWZGOR/q1hmGPzg==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:8NAuOqSs8A4NR58p1yLENto=,iv:MnB1vb+W6tT3RULUDXMfTqEMlRlMWYaDrVMUBXlSNNs=,tag:whvxwDZjETe88TV5IK1e8g==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:uc+QkMwCf90LbPFpQXa2Kyfbcg==,iv:4HQXllnoFIKYjsXjXrJTpekMQY3TpeZlYOwlau0ZXHU=,tag:1EP0trBITJMeTaFBlKtoCw==,type:str]
    DATABASE_PARAMETERS: ENC[AES256_GCM,data:cFSFr63Ap5irh0FP3tLXSUkwZ/Fb/JpYBDWXx2bB5HQAI21cTkp1cDLvGT5VCzwECjMHBM4NHLEa8I6vWeYd/tL4doc9rxE2hlkrWzCX9Fz5pRXV8/Nq0gIjPnaHCdjR589BX+8aXabFpBHkfiOVRCsRrfYzI/7DYqqsWpKjBP9IdK9C4jxPqLvjR/Zyk54+1CltPWrr7ZE=,iv:US7baJCy2Kt7tjZxRr9LBwyooUfgPlh0kOD4Ki9ckT8=,tag:Vk9pXrhE+1/YdAXIq3X+DA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:4MPoUCGfUcl6t7hjEnZhQj5qeblyWrwnIlH0NDeS0RV1Ny7/,iv:oZhcuEft+QItQ6Q/LxrdCPWSOuWKgF5VTCG2+2Uvm6E=,tag:dNWdkHCBUI+wAXBelt+vmg==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:D79EIjc=,iv:1Mz0uPtR3VWNjCRPfnWRO7CD9/QeUZ6RkJahf+G8aUM=,tag:JTLHMVFdekDuQom5Mf9PsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWlZVeE94eW1aVk5DaDNM
            a2VzU0Y0YXZWSHBESXVreGg5M3U2MFVnZTBNCmsySEpkUkEvR21aYk50aFQ4RGJQ
            d3ltTGpTVHRTNy9iaGk5ckFMM3owdjQKLS0tIFZweitFeC9LWCt0cjVaazhneHVX
            cnJmMkk5ZzI0Q3hEMnZTUXlmL1o2dlEK5orT60RxGFr1MDvc6Zk5T/6EQU18DCIy
            CidCthuNfMcVZ8VxiPnyJGRbgopeVmI686GkkDBjtwf8tIRW1n2YRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T18:57:48Z"
    mac: ENC[AES256_GCM,data:EPdlYzysENquJvZX4Eh5sN/ITXaJTggzkTQiZMPgG/p+KKszJMNOz8euhRJZuNp1wh0rAEitdvsFOeIQwp2tBYBvvh2VIzaYyYhqnebuFZ0Bs3mEdfnzVS2I4uPz7SlDMGFbTwZa9i/tfcIGLpMEauDbMzvoZVXxwztpj698jjA=,iv:Pc7iq6+8OHmhozr7LVXJoRBoqaWcuePfz8AuPgAN3GY=,tag:CeMIE2ed6Oo7Y/8B1X6+Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
